/**
 * Embedded TFLite model blob (temperature forecaster)
 * 
 * The underlying arrays are generated by your build step
 * (xxd or tensorflow lite converter). Length is preserved as an unsigned int
 * for compatibility; define MODEL_..._TFLITE_LEN aliases if you prefer.
 */

#pragma once
#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char model_int8_tflite[];
extern const unsigned int  model_int8_tflite_len;

#ifdef __cplusplus
}
#endif
#ifndef MODEL_TFLITE_LEN
#define MODEL_TFLITE_LEN model_int8_tflite_len
#endif
